In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/spaceship-titanic/sample_submission.csv
/kaggle/input/spaceship-titanic/train.csv
/kaggle/input/spaceship-titanic/test.csv

In [2]:
train_data = pd.read_csv('/kaggle/input/spaceship-titanic/train.csv')

In [3]:
train_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [4]:
train_data = pd.get_dummies(train_data, columns = ['HomePlanet', 'Destination'])
train_data.head()

,PassengerId,CryoSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,0001_01,False,B/0/P,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False,0,1,0,0,0,1
1,0002_01,False,F/0/S,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True,1,0,0,0,0,1
2,0003_01,False,A/0/S,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False,0,1,0,0,0,1
3,0003_02,False,A/0/S,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False,0,1,0,0,0,1
4,0004_01,False,F/1/S,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True,1,0,0,0,0,1

In [5]:
target = train_data['Transported']
target.head()

0    False
1     True
2    False
3    False
4     True
Name: Transported, dtype: bool

In [6]:
train_data = train_data.drop(columns = ['PassengerId', 'Name'])
train_data.head()

,CryoSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,False,B/0/P,39.0,False,0.0,0.0,0.0,0.0,0.0,False,0,1,0,0,0,1
1,False,F/0/S,24.0,False,109.0,9.0,25.0,549.0,44.0,True,1,0,0,0,0,1
2,False,A/0/S,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,0,1,0,0,0,1
3,False,A/0/S,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,0,1,0,0,0,1
4,False,F/1/S,16.0,False,303.0,70.0,151.0,565.0,2.0,True,1,0,0,0,0,1

In [7]:
train_data.Cabin = train_data.Cabin.astype('category').cat.codes

In [8]:
train_data.head()

,CryoSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,False,149,39.0,False,0.0,0.0,0.0,0.0,0.0,False,0,1,0,0,0,1
1,False,2184,24.0,False,109.0,9.0,25.0,549.0,44.0,True,1,0,0,0,0,1
2,False,1,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,0,1,0,0,0,1
3,False,1,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,0,1,0,0,0,1
4,False,2186,16.0,False,303.0,70.0,151.0,565.0,2.0,True,1,0,0,0,0,1

In [9]:
train_data[:][['Cabin','Age']]

      Cabin   Age
0       149  39.0
1      2184  24.0
2         1  58.0
3         1  33.0
4      2186  16.0
...     ...   ...
8688    146  41.0
8689   5280  18.0
8690   5285  26.0
8691   2131  32.0
8692   2131  44.0

[8693 rows x 2 columns]

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
sc = StandardScaler()

In [12]:
train_data.head()

,CryoSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,False,149,39.0,False,0.0,0.0,0.0,0.0,0.0,False,0,1,0,0,0,1
1,False,2184,24.0,False,109.0,9.0,25.0,549.0,44.0,True,1,0,0,0,0,1
2,False,1,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,0,1,0,0,0,1
3,False,1,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,0,1,0,0,0,1
4,False,2186,16.0,False,303.0,70.0,151.0,565.0,2.0,True,1,0,0,0,0,1

In [13]:
train_data[['Cabin', 'Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']] = sc.fit_transform(train_data[['Cabin', 'Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']])

In [14]:
train_data.head()

,CryoSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,False,-1.457967,0.702095,False,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,False,0,1,0,0,0,1
1,False,-0.444889,-0.333233,False,-0.173528,-0.278689,-0.245971,0.209267,-0.227692,True,1,0,0,0,0,1
2,False,-1.531645,2.013510,True,-0.272527,1.934922,-0.287317,5.634034,-0.223327,False,0,1,0,0,0,1
3,False,-1.531645,0.287964,False,-0.337025,0.511931,0.326250,2.655075,-0.097634,False,0,1,0,0,0,1
4,False,-0.443894,-0.885407,False,0.117466,-0.240833,-0.037590,0.223344,-0.264352,True,1,0,0,0,0,1

In [15]:
test_data = pd.read_csv('/kaggle/input/spaceship-titanic/test.csv')

In [16]:
test_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez

In [17]:
test_data = test_data.drop(columns = ['PassengerId', 'Name'])
test_data.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0
1,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0
2,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0
3,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0
4,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0

In [18]:
test_data.Cabin = test_data.Cabin.astype('category').cat.codes

In [19]:
test_data.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,Earth,True,2784,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0
1,Earth,False,1867,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0
2,Europa,True,257,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0
3,Europa,False,259,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0
4,Earth,False,1940,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0

In [20]:
test_data[['Cabin', 'Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']] = sc.transform(test_data[['Cabin', 'Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']])

In [21]:
test_data.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,Earth,True,-0.146193,TRAPPIST-1e,-0.126167,False,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098
1,Earth,False,-0.602700,TRAPPIST-1e,-0.678342,False,-0.337025,-0.278689,-0.287317,2.209903,-0.266098
2,Europa,True,-1.404201,55 Cancri e,0.149920,False,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098
3,Europa,False,-1.403206,TRAPPIST-1e,0.633073,False,-0.337025,3.843828,-0.287317,-0.114494,0.244530
4,Earth,False,-0.566359,TRAPPIST-1e,-0.609320,False,-0.322026,-0.284274,0.762859,-0.273736,-0.266098

In [22]:
test_data = pd.get_dummies(test_data, columns = ['HomePlanet', 'Destination'])
test_data.head()

,CryoSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,True,-0.146193,-0.126167,False,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,1,0,0,0,0,1
1,False,-0.602700,-0.678342,False,-0.337025,-0.278689,-0.287317,2.209903,-0.266098,1,0,0,0,0,1
2,True,-1.404201,0.149920,False,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,0,1,0,1,0,0
3,False,-1.403206,0.633073,False,-0.337025,3.843828,-0.287317,-0.114494,0.244530,0,1,0,0,0,1
4,False,-0.566359,-0.609320,False,-0.322026,-0.284274,0.762859,-0.273736,-0.266098,1,0,0,0,0,1

In [23]:
train_data = train_data.drop(columns = ['Transported'])
train_data.head()

,CryoSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,False,-1.457967,0.702095,False,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,0,1,0,0,0,1
1,False,-0.444889,-0.333233,False,-0.173528,-0.278689,-0.245971,0.209267,-0.227692,1,0,0,0,0,1
2,False,-1.531645,2.013510,True,-0.272527,1.934922,-0.287317,5.634034,-0.223327,0,1,0,0,0,1
3,False,-1.531645,0.287964,False,-0.337025,0.511931,0.326250,2.655075,-0.097634,0,1,0,0,0,1
4,False,-0.443894,-0.885407,False,0.117466,-0.240833,-0.037590,0.223344,-0.264352,1,0,0,0,0,1

In [24]:
target.head()

0    False
1     True
2    False
3    False
4     True
Name: Transported, dtype: bool

In [25]:
from sklearn.impute import SimpleImputer
my_imputer = SimpleImputer()
train_data = my_imputer.fit_transform(train_data)
type(train_data)

numpy.ndarray

In [26]:
from sklearn.svm import SVC
svm = SVC(kernel='rbf', C=0.1, random_state=1)
svm.fit(train_data,target)
from sklearn.metrics import accuracy_score
predicted = svm.predict(train_data)
print(accuracy_score(target, predicted))

0.7875301967099966

In [27]:
adder = pd.read_csv('/kaggle/input/spaceship-titanic/train.csv')

In [28]:
adder.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [29]:
adder = adder['PassengerId']
type(adder)
adder.to_frame()

     PassengerId
0        0001_01
1        0002_01
2        0003_01
3        0003_02
4        0004_01
...          ...
8688     9276_01
8689     9278_01
8690     9279_01
8691     9280_01
8692     9280_02

[8693 rows x 1 columns]

In [30]:
type(train_data)

numpy.ndarray

In [31]:
type(adder)

pandas.core.series.Series

In [32]:
train_data = pd.DataFrame(train_data, columns = ['CyroSleep', 'Cabin', 'Age', 'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'HomePlanet_Earth', 'HomePlanet_Europa', 'HomePlanet_Mars','Destination_55 Cancri e', 'Destination_PSO J318.5-22', 'Destination_TRAPPIST-1e'])

In [33]:
train_data = pd.concat([train_data, adder], axis=1, join='inner')
train_data

,CyroSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,PassengerId
0,0.0,-1.457967,0.702095,0.0,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,0.0,1.0,0.0,0.0,0.0,1.0,0001_01
1,0.0,-0.444889,-0.333233,0.0,-0.173528,-0.278689,-0.245971,0.209267,-0.227692,1.0,0.0,0.0,0.0,0.0,1.0,0002_01
2,0.0,-1.531645,2.013510,1.0,-0.272527,1.934922,-0.287317,5.634034,-0.223327,0.0,1.0,0.0,0.0,0.0,1.0,0003_01
3,0.0,-1.531645,0.287964,0.0,-0.337025,0.511931,0.326250,2.655075,-0.097634,0.0,1.0,0.0,0.0,0.0,1.0,0003_02
4,0.0,-0.443894,-0.885407,0.0,0.117466,-0.240833,-0.037590,0.223344,-0.264352,1.0,0.0,0.0,0.0,0.0,1.0,0004_01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,0.0,-1.459460,0.840138,1.0,-0.337025,3.947464,-0.287317,1.171754,-0.201506,0.0,1.0,0.0,1.0,0.0,0.0,9276_01
8689,1.0,1.096382,-0.747364,0.0,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,1.0,0.0,0.0,0.0,1.0,0.0,9278_01
8690,0.0,1.098871,-0.195189,0.0,-0.337025,-0.284274,2.808634,-0.272856,-0.266098,1.0,0.0,0.0,0.0,0.0,1.0,9279_01
8691,0.0,-0.471274,0.218942,0.0,-0.337025,0.366715,-0.287317,0.036829,2.557627,0.0,1.0,0.0,1.0,0.0,0.0,9280_01
8692,0.0,-0.471274,1.047204,0.0,-0.148029,2.625008,-0.287317,-0.273736,-0.255623,0.0,1.0,0.0,0.0,0.0,1.0,9280_02

In [34]:
test_data

,CryoSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,True,-0.146193,-0.126167,False,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,1,0,0,0,0,1
1,False,-0.602700,-0.678342,False,-0.337025,-0.278689,-0.287317,2.209903,-0.266098,1,0,0,0,0,1
2,True,-1.404201,0.149920,False,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,0,1,0,1,0,0
3,False,-1.403206,0.633073,False,-0.337025,3.843828,-0.287317,-0.114494,0.244530,0,1,0,0,0,1
4,False,-0.566359,-0.609320,False,-0.322026,-0.284274,0.762859,-0.273736,-0.266098,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,True,-0.198465,0.356986,False,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,1,0,0,0,0,1
4273,False,-1.532641,0.909160,False,-0.337025,0.241358,-0.259202,-0.264938,-0.140405,1,0,0,0,0,1
4274,True,-1.232451,NaN,False,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,0,0,1,1,0,0
4275,False,-1.231953,NaN,False,-0.337025,1.378882,-0.287317,-0.273736,0.190412,0,1,0,0,0,0
4276,True,-0.197967,0.978182,False,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,1,0,0,0,1,0

In [35]:
from sklearn.impute import SimpleImputer
my_imputer = SimpleImputer()
test_data = my_imputer.fit_transform(test_data)
type(test_data)

numpy.ndarray

In [36]:
predictions = svm.predict(test_data)

# output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
# output.to_csv('submission.csv', index=False)
# print("Your submission was successfully saved!")

In [37]:
adder = pd.read_csv('/kaggle/input/spaceship-titanic/test.csv')

In [38]:
adder

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
4273,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
4274,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
4275,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [39]:
adder = adder['PassengerId']
type(adder)
adder.to_frame()

     PassengerId
0        0013_01
1        0018_01
2        0019_01
3        0021_01
4        0023_01
...          ...
4272     9266_02
4273     9269_01
4274     9271_01
4275     9273_01
4276     9277_01

[4277 rows x 1 columns]

In [40]:
test_data = pd.DataFrame(test_data, columns = ['CyroSleep', 'Cabin', 'Age', 'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'HomePlanet_Earth', 'HomePlanet_Europa', 'HomePlanet_Mars','Destination_55 Cancri e', 'Destination_PSO J318.5-22', 'Destination_TRAPPIST-1e'])

In [41]:
test_data = pd.concat([test_data, adder], axis=1, join='inner')
test_data

,CyroSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,PassengerId
0,1.0,-0.146193,-0.126167,0.0,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,1.0,0.0,0.0,0.0,0.0,1.0,0013_01
1,0.0,-0.602700,-0.678342,0.0,-0.337025,-0.278689,-0.287317,2.209903,-0.266098,1.0,0.0,0.0,0.0,0.0,1.0,0018_01
2,1.0,-1.404201,0.149920,0.0,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,0.0,1.0,0.0,1.0,0.0,0.0,0019_01
3,0.0,-1.403206,0.633073,0.0,-0.337025,3.843828,-0.287317,-0.114494,0.244530,0.0,1.0,0.0,0.0,0.0,1.0,0021_01
4,0.0,-0.566359,-0.609320,0.0,-0.322026,-0.284274,0.762859,-0.273736,-0.266098,1.0,0.0,0.0,0.0,0.0,1.0,0023_01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,1.0,-0.198465,0.356986,0.0,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,1.0,0.0,0.0,0.0,0.0,1.0,9266_02
4273,0.0,-1.532641,0.909160,0.0,-0.337025,0.241358,-0.259202,-0.264938,-0.140405,1.0,0.0,0.0,0.0,0.0,1.0,9269_01
4274,1.0,-1.232451,-0.011719,0.0,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,0.0,0.0,1.0,1.0,0.0,0.0,9271_01
4275,0.0,-1.231953,-0.011719,0.0,-0.337025,1.378882,-0.287317,-0.273736,0.190412,0.0,1.0,0.0,0.0,0.0,0.0,9273_01
4276,1.0,-0.197967,0.978182,0.0,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,1.0,0.0,0.0,0.0,1.0,0.0,9277_01

In [42]:
type(predictions)

numpy.ndarray

In [43]:
predictions = pd.DataFrame(predictions, columns=['Prediction'])

In [44]:
predictions

      Prediction
0           True
1          False
2           True
3           True
4          False
...          ...
4272        True
4273       False
4274        True
4275        True
4276        True

[4277 rows x 1 columns]

In [45]:
test_data = pd.concat([test_data, predictions], axis=1, join='inner')

In [46]:
test_data

,CyroSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,PassengerId,Prediction
0,1.0,-0.146193,-0.126167,0.0,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,1.0,0.0,0.0,0.0,0.0,1.0,0013_01,True
1,0.0,-0.602700,-0.678342,0.0,-0.337025,-0.278689,-0.287317,2.209903,-0.266098,1.0,0.0,0.0,0.0,0.0,1.0,0018_01,False
2,1.0,-1.404201,0.149920,0.0,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,0.0,1.0,0.0,1.0,0.0,0.0,0019_01,True
3,0.0,-1.403206,0.633073,0.0,-0.337025,3.843828,-0.287317,-0.114494,0.244530,0.0,1.0,0.0,0.0,0.0,1.0,0021_01,True
4,0.0,-0.566359,-0.609320,0.0,-0.322026,-0.284274,0.762859,-0.273736,-0.266098,1.0,0.0,0.0,0.0,0.0,1.0,0023_01,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,1.0,-0.198465,0.356986,0.0,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,1.0,0.0,0.0,0.0,0.0,1.0,9266_02,True
4273,0.0,-1.532641,0.909160,0.0,-0.337025,0.241358,-0.259202,-0.264938,-0.140405,1.0,0.0,0.0,0.0,0.0,1.0,9269_01,False
4274,1.0,-1.232451,-0.011719,0.0,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,0.0,0.0,1.0,1.0,0.0,0.0,9271_01,True
4275,0.0,-1.231953,-0.011719,0.0,-0.337025,1.378882,-0.287317,-0.273736,0.190412,0.0,1.0,0.0,0.0,0.0,0.0,9273_01,True
4276,1.0,-0.197967,0.978182,0.0,-0.337025,-0.284274,-0.287317,-0.273736,-0.266098,1.0,0.0,0.0,0.0,1.0,0.0,9277_01,True

In [47]:
output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Transported': test_data.Prediction})

In [48]:
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!